### ISSUE TITLE
Reopen cause I forgot to respond

### ISSUE THREAD

**Issue by MakeShiftArtist** [revoltchat/documentation#16]
I previously opened an issue about documentation links not working, and the links that were given with the response were not the same ones in the documentation.
This page [overview.md](https://github.com/revoltchat/documentation/blob/master/docs/websockets/overview.md), has 3 urls that lead to a 404. This made navigating documentation difficult and I ended up forgetting about it.

**Comment by Rexogamer** [comment]
Due to different file structures, it seems as though links need to be 404s on GitHub to work with Docusaurus and vice versa. I would strongly advise browsing these docs on [the site itself](https://developers.revolt.chat/), as this provides a much nicer interface for reading and the links and images all seem to be valid/working. If you see any errors on the site itself, please let us know. Thanks!
